### ISSUE TITLE
Todo list (not exhaustive)

### ISSUE THREAD

**Issue by Kreston101** [Kreston101/ARLyfProj#3]
- [x] Fix tiles not moving properly
- [x] Randomiser
- [x] Texture the wall
- [x] Timer
- [ ] More difficulties?
- [x] Test in AR

**Comment by Kreston101** [comment]
Project completed, additional difficulties was found to be unnecessary as the base puzzle took quite some time to solve already
